version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - insight-network

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    networks:
      - insight-network
    depends_on:
      - backend

networks:
  insight-network:
    driver: bridge
