"""Add role default to User

Revision ID: 09453dee6b6b
Revises: 2d688f7b6e07
Create Date: 2025-04-07 12:16:34.825249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09453dee6b6b'
down_revision: Union[str, None] = '2d688f7b6e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=sa.Enum('USER', 'ADMIN', name='roleenum'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.Enum('USER', 'ADMIN', name='roleenum'),
                    type_=mysql.VARCHAR(length=50),
                    existing_nullable=False)
    # ### end Alembic commands ###
