"""initial

Revision ID: 2af693c21e54
Revises:
Create Date: 2025-04-07 12:02:08.624151

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '2af693c21e54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
