"""Update alerts table to include alarm details

Revision ID: 641a3201234b
Revises: 3daf9ae5e508
Create Date: 2025-04-08 12:08:59.290198

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '641a3201234b'
down_revision: Union[str, None] = '3daf9ae5e508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('table_name', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('field', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('threshold', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('chats', 'createdAt',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    op.alter_column('chats', 'updatedAt',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    op.alter_column('chats', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.drop_constraint('chats_ibfk_1', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'name',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('users', 'email',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('users', 'password',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('users', 'role',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('users', 'password',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('users', 'email',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('users', 'name',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_ibfk_1', 'chats', 'users', ['user_id'], ['id'])
    op.alter_column('chats', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.alter_column('chats', 'updatedAt',
                    existing_type=mysql.DATETIME(),
                    nullable=True)
    op.alter_column('chats', 'createdAt',
                    existing_type=mysql.DATETIME(),
                    nullable=True)
    op.drop_column('alerts', 'description')
    op.drop_column('alerts', 'threshold')
    op.drop_column('alerts', 'field')
    op.drop_column('alerts', 'table_name')
    # ### end Alembic commands ###
