"""automatic dates

Revision ID: 84dd80930009
Revises: a344ce864f5f
Create Date: 2025-04-21 23:51:20.170747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84dd80930009'
down_revision: Union[str, None] = 'a344ce864f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('alerts', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('datasets', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('datasets', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('questions', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('questions', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('responses', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('responses', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('responses', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('questions', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('questions', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('datasets', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('datasets', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('alerts', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('alerts', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###