"""initial migration

Revision ID: 97c4d19f7621
Revises: 
Create Date: 2025-04-22 19:08:19.935323

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '97c4d19f7621'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('file_path', sa.String(length=255), nullable=True),
                    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(length=255), nullable=False),
                    sa.Column('username', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('role', sa.Enum('USER', 'ADMIN', name='roleenum'), nullable=False),
                    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alerts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('condition', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('field', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('table_name', sa.String(length=255), nullable=True),
                    sa.Column('threshold', sa.Integer(), nullable=True),
                    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('chats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(length=255), nullable=True),
                    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('responses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('query_result', sa.JSON(), nullable=True),
                    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
