"""Initial migration

Revision ID: 9fbf473ec06d
Revises: 
Create Date: 2025-05-20 20:02:36.532957

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '9fbf473ec06d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
