"""Models configured

Revision ID: c6752bf9b0d9
Revises: 3daf9ae5e508
Create Date: 2025-03-15 22:26:43.484359

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import mysql
from sqlalchemy.exc import OperationalError

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6752bf9b0d9'
down_revision: Union[str, None] = '3daf9ae5e508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Intentar eliminar las tablas si existen
    try:
        # Usar SQLAlchemy Inspector para verificar si la tabla existe
        inspector = inspect(op.get_bind())
        if 'alerts' in inspector.get_table_names():
            op.drop_index('ix_alerts_id', table_name='alerts')
            op.drop_table('alerts')
    except OperationalError:
        pass  # La tabla 'alerts' no existe, continuar sin hacer nada

    try:
        if 'responses' in inspector.get_table_names():
            op.drop_index('ix_responses_id', table_name='responses')
            op.drop_table('responses')
    except OperationalError:
        pass

    try:
        if 'visual_resources' in inspector.get_table_names():
            op.drop_index('ix_visual_resources_id', table_name='visual_resources')
            op.drop_table('visual_resources')
    except OperationalError:
        pass

    try:
        if 'users' in inspector.get_table_names():
            op.drop_index('ix_users_email', table_name='users')
            op.drop_index('ix_users_id', table_name='users')
            op.drop_table('users')
    except OperationalError:
        pass

    try:
        if 'questions' in inspector.get_table_names():
            op.drop_index('ix_questions_id', table_name='questions')
            op.drop_table('questions')
    except OperationalError:
        pass

    try:
        if 'chats' in inspector.get_table_names():
            op.drop_index('ix_chats_id', table_name='chats')
            op.drop_table('chats')
    except OperationalError:
        pass

    try:
        if 'datasets' in inspector.get_table_names():
            op.drop_index('ix_datasets_id', table_name='datasets')
            op.drop_table('datasets')
    except OperationalError:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('file', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
                    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
                    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='datasets_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_datasets_id', 'datasets', ['id'], unique=False)
    op.create_table('chats',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
                    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
                    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chats_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_chats_id', 'chats', ['id'], unique=False)
    op.create_table('questions',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
                    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
                    sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='questions_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
                    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
                    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('visual_resources',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
                    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
                    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
                    sa.Column('response_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], name='visual_resources_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_visual_resources_id', 'visual_resources', ['id'], unique=False)
    op.create_table('responses',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
                    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
                    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='responses_ibfk_1'),
                    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='responses_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_responses_id', 'responses', ['id'], unique=False)
    op.create_table('alerts',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('condition', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
                    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
                    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='alerts_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_alerts_id', 'alerts', ['id'], unique=False)
    # ### end Alembic commands ###
