"""initial

<<<<<<<< HEAD:backend/alembic/versions/bb1191e7de16_initial.py
Revision ID: bb1191e7de16
Revises: 
Create Date: 2025-04-07 22:18:51.193280
========
Revision ID: dd9cf39d31e7
Revises: 
Create Date: 2025-04-22 16:51:25.530403
>>>>>>>> fixes:backend/alembic/versions/dd9cf39d31e7_initial_migration.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:backend/alembic/versions/bb1191e7de16_initial.py
revision: str = 'bb1191e7de16'
========
revision: str = 'dd9cf39d31e7'
>>>>>>>> fixes:backend/alembic/versions/dd9cf39d31e7_initial_migration.py
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###