name: Backend Linter

on:
  push:
    paths:
      - "backend/**"
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements-linter.txt

      - name: Run isort (organize imports)
        working-directory: backend
        run: isort .

      - name: Run autoflake (remove unused imports/variables)
        working-directory: backend
        run: autoflake --remove-all-unused-imports --recursive --in-place .

      - name: Run autopep8 (auto format)
        working-directory: backend
        run: autopep8 --recursive --in-place .

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.changes == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout ${{ github.head_ref }}
          
          # Guardar cambios antes de hacer pull
          git stash
          git pull --rebase origin ${{ github.head_ref }} || echo "No remote changes to rebase"
          git stash pop || echo "No stashed changes to apply"

          git add .
          git commit -m "style: run linter"
          git push origin ${{ github.head_ref }}
