name: Backend Linter

on:
  push:
    paths:
      - "backend/**"
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements-linter.txt

      - name: Run isort (organize imports)
        run: |
          cd backend
          isort .

      - name: Run autoflake (remove unused imports/variables)
        run: |
          cd backend
          autoflake --remove-all-unused-imports --recursive --in-place .

      - name: Run autopep8 (auto format)
        run: |
          cd backend
          autopep8 --recursive --in-place .

      - name: Check for changes
        id: git-check
        run: |
          git status
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "chore: apply linter fixes"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
