name: Frontend Linter

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Prettier (formatting)
        run: |
          cd frontend
          npx prettier --write "src/**/*.{ts,vue,js,json,css,scss,md}"

      - name: Run ESLint (linting)
        run: |
          cd frontend
          npx eslint src --fix

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: ${{ steps.git-check.outputs.changes == 'true' }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout ${{ github.head_ref }}
          
          # Guardar cambios antes de hacer pull
          git stash
          git pull --rebase origin ${{ github.head_ref }} || echo "No remote changes to rebase"
          git stash pop || echo "No stashed changes to apply"

          git add .
          git commit -m "style: run linter"
          git push origin ${{ github.head_ref }}
