name: Frontend Linter

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Prettier (formatting)
        run: |
          cd frontend
          npx prettier --write "src/**/*.{ts,vue,js,json,css,scss,md}"

      - name: Run ESLint (linting)
        run: |
          cd frontend
          npx eslint src --fix

          - name: Commit and push changes
          run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git fetch origin ${{ github.head_ref }}  # Fetch latest changes
            git checkout ${{ github.head_ref }}      # Switch to the correct branch
            git pull --rebase origin ${{ github.head_ref }} || echo "No remote changes to rebase"
            git add .
            git diff --cached --quiet || (git commit -m "style: run linter" && git push origin HEAD:${{ github.head_ref }})
